"""Init tables

Revision ID: 958e7330a8fd
Revises: 
Create Date: 2023-11-06 23:19:42.621756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '958e7330a8fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fullname', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todo_repos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_repos_user_id'), 'todo_repos', ['user_id'], unique=False)
    op.create_table('daily_todos',
    sa.Column('todo_repo_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['todo_repo_id'], ['todo_repos.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('todo_repo_id', 'date')
    )
    op.create_table('daily_todo_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('todo_repo_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['todo_repo_id', 'date'], ['daily_todos.todo_repo_id', 'daily_todos.date'], name='fk_daily_todo_task_daily_todo'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('fk_daily_todo_task_daily_todo', 'daily_todo_tasks', ['todo_repo_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fk_daily_todo_task_daily_todo', table_name='daily_todo_tasks')
    op.drop_table('daily_todo_tasks')
    op.drop_table('daily_todos')
    op.drop_index(op.f('ix_todo_repos_user_id'), table_name='todo_repos')
    op.drop_table('todo_repos')
    op.drop_table('users')
    # ### end Alembic commands ###
